import type { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';

import { ProgramType, ModuleType } from '../types';

import Program from '../components/Program';
import Card from '../components/Card';

export const getServerSideProps = async () => {
  const { data } = await axios.get('https://api-moscow-mba.herokuapp.com/products');
  return {
    props: {
      data: data.filter((item: ProgramType) => item.specializedSubjects.length >= 10).slice(0, 5),
    },
  };
};

type HomeProps = {
  data: ProgramType[];
};

const Home: NextPage<HomeProps> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Test task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h2>Специализированные дисциплины</h2>
        {data.map((item) => (
          <Program key={item.id} program={item} />
        ))}

        <div className="cards">
          <Card cardBg="card_red" title="Практические модули">
            <p>
              Работа над собственными проектами: практика групповых взаимодействий, кейс-методы,
              эссе
            </p>
          </Card>
          <Card cardBg="card_black" title="Итоговая аттестация">
            <div className="">
              <ul>
                <li>
                  <span>
                    Бизнес-проектирование (подготовка итоговой аттестационной работы,
                    консультирование по бизнес-проектированию)
                  </span>
                </li>
                <li>
                  <span>Защита итоговой аттестационной работы</span>
                </li>
              </ul>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default Home;
